spring:
  application:
    name: TaskRacer
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskRacer_test
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    default-schema: social
    liquibase-schema: liquibase

server:
  servlet:
    context-path: /api

jwt:
  secret-key: "b5274918-5bb3-49e1-8ed3-5cbb339d77b8"