spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    default-schema: social
    liquibase-schema: liquibase

task-racer:
  jwt-secret-key: "b5274918-5bb3-49e1-8ed3-5cbb339d77b8"
  private-key: "aca71827026bafe927b66952c6e3eb88"
  expire:
    minute: 5
    hour: 1
    day: 31
  pomodoro:
    checkpoint: 5
  allowedOrigins:
    - http://localhost:5173
    - https://taskracer.id.vn

server:
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048

springdoc:
  swagger-ui:
    path: "/docs"
  api-docs:
    path: "/api-docs"